# Site
title:              Yuan He
bio: 		    Hi! I am currently a PhD candidate in Computer Science.
uni:                University of Oxford
dept:               Department of Computer Science
description:        PhD candidate in Computer Science at University of Oxford.
reading_time:       true
words_per_minute:   200
logo:               'assets/img/2021110-circle-cropped.png'
background:         'https://images.pexels.com/photos/3774094/pexels-photo-3774094.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260'
tiled_bg:           true   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_UK
url:                https://lawhy.github.io

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   taylantatli

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              yuan.he@cs.ox.ac.uk
#twitter:           username
facebook:           yuanheoxcs
github-url:         Lawhy
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:           yuan-he-0557781aa
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
